/********************************************************************************
** Form generated from reading UI file 'home.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_HOME_H
#define UI_HOME_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Home
{
public:
    QTabWidget *tabWidget;
    QWidget *add_judge;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QCheckBox *checkBox;
    QCheckBox *checkBox_2;
    QCheckBox *checkBox_3;
    QCheckBox *checkBox_4;
    QCheckBox *checkBox_5;
    QCheckBox *checkBox_6;
    QCheckBox *checkBox_7;
    QPushButton *clear_judge;
    QPushButton *ad_judge;
    QPushButton *show_judge;
    QWidget *add_grp;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_8;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_10;
    QLineEdit *lineEdit_11;
    QPushButton *clear_group;
    QPushButton *ad_grp;
    QPushButton *show_grpinfo;
    QLabel *label_24;
    QLineEdit *lineEdit_16;
    QWidget *add_marks;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLineEdit *lineEdit_12;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QPushButton *clear_marks;
    QPushButton *ad_marks;
    QPushButton *show_marksentry;
    QLabel *label_25;
    QWidget *view_res;
    QLabel *label_20;
    QComboBox *comboBox;
    QLabel *label_21;
    QPushButton *view_oresult;
    QPushButton *prnt_oresult;
    QFrame *line;
    QLabel *label_22;
    QLabel *label_23;
    QLineEdit *lineEdit_15;
    QPushButton *view_presult;
    QPushButton *prnt_presult;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QProgressBar *progressBar;
    QLabel *label_26;
    QPushButton *about;

    void setupUi(QDialog *Home)
    {
        if (Home->objectName().isEmpty())
            Home->setObjectName(QStringLiteral("Home"));
        Home->resize(863, 682);
        Home->setMinimumSize(QSize(863, 682));
        Home->setMaximumSize(QSize(863, 682));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 41, 61, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(0, 61, 91, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(0, 51, 76, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(0, 20, 30, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(0, 27, 40, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush7(QColor(255, 255, 220, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        Home->setPalette(palette);
        QIcon icon;
        icon.addFile(QStringLiteral("../../INC17Docs/2inc17.png"), QSize(), QIcon::Normal, QIcon::Off);
        Home->setWindowIcon(icon);
        tabWidget = new QTabWidget(Home);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 80, 841, 571));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        QBrush brush8(QColor(127, 127, 127, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush8);
        QBrush brush9(QColor(170, 170, 170, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush9);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        tabWidget->setPalette(palette1);
        QFont font;
        font.setBold(false);
        font.setWeight(50);
        tabWidget->setFont(font);
        tabWidget->setTabShape(QTabWidget::Rounded);
        add_judge = new QWidget();
        add_judge->setObjectName(QStringLiteral("add_judge"));
        label_4 = new QLabel(add_judge);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(190, 50, 81, 41));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_4->setPalette(palette2);
        QFont font1;
        font1.setPointSize(13);
        label_4->setFont(font1);
        label_5 = new QLabel(add_judge);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(190, 100, 81, 41));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_5->setPalette(palette3);
        label_5->setFont(font1);
        label_6 = new QLabel(add_judge);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(190, 140, 81, 41));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_6->setPalette(palette4);
        label_6->setFont(font1);
        label_7 = new QLabel(add_judge);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(300, 190, 151, 41));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_7->setPalette(palette5);
        label_7->setFont(font1);
        lineEdit = new QLineEdit(add_judge);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setEnabled(true);
        lineEdit->setGeometry(QRect(280, 60, 113, 24));
        lineEdit_2 = new QLineEdit(add_judge);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(280, 110, 341, 24));
        lineEdit_2->setMaxLength(49);
        lineEdit_3 = new QLineEdit(add_judge);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(280, 150, 341, 24));
        lineEdit_3->setMaxLength(50);
        checkBox = new QCheckBox(add_judge);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(190, 230, 431, 21));
        checkBox_2 = new QCheckBox(add_judge);
        checkBox_2->setObjectName(QStringLiteral("checkBox_2"));
        checkBox_2->setGeometry(QRect(190, 260, 431, 21));
        checkBox_3 = new QCheckBox(add_judge);
        checkBox_3->setObjectName(QStringLiteral("checkBox_3"));
        checkBox_3->setGeometry(QRect(190, 290, 431, 21));
        checkBox_4 = new QCheckBox(add_judge);
        checkBox_4->setObjectName(QStringLiteral("checkBox_4"));
        checkBox_4->setGeometry(QRect(190, 320, 431, 21));
        checkBox_5 = new QCheckBox(add_judge);
        checkBox_5->setObjectName(QStringLiteral("checkBox_5"));
        checkBox_5->setGeometry(QRect(190, 350, 431, 21));
        checkBox_6 = new QCheckBox(add_judge);
        checkBox_6->setObjectName(QStringLiteral("checkBox_6"));
        checkBox_6->setGeometry(QRect(190, 380, 431, 21));
        checkBox_7 = new QCheckBox(add_judge);
        checkBox_7->setObjectName(QStringLiteral("checkBox_7"));
        checkBox_7->setGeometry(QRect(190, 410, 431, 21));
        clear_judge = new QPushButton(add_judge);
        clear_judge->setObjectName(QStringLiteral("clear_judge"));
        clear_judge->setGeometry(QRect(190, 450, 161, 41));
        clear_judge->setAutoDefault(true);
        ad_judge = new QPushButton(add_judge);
        ad_judge->setObjectName(QStringLiteral("ad_judge"));
        ad_judge->setGeometry(QRect(430, 450, 161, 41));
        ad_judge->setAutoDefault(true);
        show_judge = new QPushButton(add_judge);
        show_judge->setObjectName(QStringLiteral("show_judge"));
        show_judge->setGeometry(QRect(660, 450, 151, 41));
        tabWidget->addTab(add_judge, QString());
        add_grp = new QWidget();
        add_grp->setObjectName(QStringLiteral("add_grp"));
        label_8 = new QLabel(add_grp);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(110, 40, 81, 41));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_8->setPalette(palette6);
        label_8->setFont(font1);
        label_9 = new QLabel(add_grp);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(110, 80, 81, 41));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_9->setPalette(palette7);
        label_9->setFont(font1);
        label_10 = new QLabel(add_grp);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(110, 210, 81, 41));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_10->setPalette(palette8);
        label_10->setFont(font1);
        label_11 = new QLabel(add_grp);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(110, 250, 81, 41));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_11->setPalette(palette9);
        label_11->setFont(font1);
        label_12 = new QLabel(add_grp);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(100, 310, 181, 41));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_12->setPalette(palette10);
        label_12->setFont(font1);
        label_13 = new QLabel(add_grp);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(100, 340, 181, 41));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_13->setPalette(palette11);
        label_13->setFont(font1);
        label_14 = new QLabel(add_grp);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(100, 370, 181, 41));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_14->setPalette(palette12);
        label_14->setFont(font1);
        label_15 = new QLabel(add_grp);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(100, 400, 181, 41));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_15->setPalette(palette13);
        label_15->setFont(font1);
        label_16 = new QLabel(add_grp);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(100, 430, 181, 41));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_16->setPalette(palette14);
        label_16->setFont(font1);
        lineEdit_4 = new QLineEdit(add_grp);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(210, 50, 113, 24));
        lineEdit_4->setMaxLength(10);
        lineEdit_5 = new QLineEdit(add_grp);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(200, 220, 511, 31));
        lineEdit_5->setMaxLength(100);
        lineEdit_6 = new QLineEdit(add_grp);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(200, 260, 511, 31));
        lineEdit_6->setMaxLength(100);
        lineEdit_7 = new QLineEdit(add_grp);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(240, 320, 471, 24));
        lineEdit_7->setMaxLength(50);
        lineEdit_8 = new QLineEdit(add_grp);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(240, 350, 471, 24));
        lineEdit_8->setMaxLength(50);
        lineEdit_9 = new QLineEdit(add_grp);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(240, 380, 471, 24));
        lineEdit_9->setMaxLength(50);
        lineEdit_10 = new QLineEdit(add_grp);
        lineEdit_10->setObjectName(QStringLiteral("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(240, 410, 471, 24));
        lineEdit_10->setMaxLength(50);
        lineEdit_11 = new QLineEdit(add_grp);
        lineEdit_11->setObjectName(QStringLiteral("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(240, 440, 471, 24));
        lineEdit_11->setMaxLength(50);
        clear_group = new QPushButton(add_grp);
        clear_group->setObjectName(QStringLiteral("clear_group"));
        clear_group->setGeometry(QRect(100, 490, 200, 41));
        ad_grp = new QPushButton(add_grp);
        ad_grp->setObjectName(QStringLiteral("ad_grp"));
        ad_grp->setGeometry(QRect(370, 490, 200, 41));
        show_grpinfo = new QPushButton(add_grp);
        show_grpinfo->setObjectName(QStringLiteral("show_grpinfo"));
        show_grpinfo->setGeometry(QRect(630, 490, 181, 41));
        label_24 = new QLabel(add_grp);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(360, 60, 461, 151));
        lineEdit_16 = new QLineEdit(add_grp);
        lineEdit_16->setObjectName(QStringLiteral("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(210, 90, 113, 24));
        lineEdit_16->setMaxLength(1);
        tabWidget->addTab(add_grp, QString());
        add_marks = new QWidget();
        add_marks->setObjectName(QStringLiteral("add_marks"));
        label_17 = new QLabel(add_marks);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(260, 80, 121, 51));
        QFont font2;
        font2.setPointSize(18);
        font2.setBold(true);
        font2.setWeight(75);
        label_17->setFont(font2);
        label_18 = new QLabel(add_marks);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(260, 140, 121, 51));
        label_18->setFont(font2);
        label_19 = new QLabel(add_marks);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(260, 200, 121, 51));
        label_19->setFont(font2);
        lineEdit_12 = new QLineEdit(add_marks);
        lineEdit_12->setObjectName(QStringLiteral("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(380, 90, 141, 41));
        lineEdit_12->setMaxLength(3);
        lineEdit_13 = new QLineEdit(add_marks);
        lineEdit_13->setObjectName(QStringLiteral("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(380, 150, 141, 41));
        lineEdit_13->setMaxLength(10);
        lineEdit_14 = new QLineEdit(add_marks);
        lineEdit_14->setObjectName(QStringLiteral("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(380, 210, 141, 41));
        lineEdit_14->setMaxLength(2);
        clear_marks = new QPushButton(add_marks);
        clear_marks->setObjectName(QStringLiteral("clear_marks"));
        clear_marks->setGeometry(QRect(180, 320, 141, 41));
        ad_marks = new QPushButton(add_marks);
        ad_marks->setObjectName(QStringLiteral("ad_marks"));
        ad_marks->setGeometry(QRect(380, 320, 141, 41));
        show_marksentry = new QPushButton(add_marks);
        show_marksentry->setObjectName(QStringLiteral("show_marksentry"));
        show_marksentry->setGeometry(QRect(580, 320, 141, 41));
        label_25 = new QLabel(add_marks);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(220, 30, 381, 41));
        QFont font3;
        font3.setPointSize(14);
        font3.setBold(true);
        font3.setWeight(75);
        label_25->setFont(font3);
        tabWidget->addTab(add_marks, QString());
        view_res = new QWidget();
        view_res->setObjectName(QStringLiteral("view_res"));
        label_20 = new QLabel(view_res);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(100, 100, 121, 41));
        QFont font4;
        font4.setPointSize(12);
        font4.setBold(false);
        font4.setWeight(50);
        label_20->setFont(font4);
        comboBox = new QComboBox(view_res);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(220, 100, 501, 41));
        label_21 = new QLabel(view_res);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(380, 40, 131, 21));
        QFont font5;
        font5.setPointSize(15);
        font5.setBold(true);
        font5.setWeight(75);
        label_21->setFont(font5);
        view_oresult = new QPushButton(view_res);
        view_oresult->setObjectName(QStringLiteral("view_oresult"));
        view_oresult->setGeometry(QRect(220, 170, 171, 41));
        prnt_oresult = new QPushButton(view_res);
        prnt_oresult->setObjectName(QStringLiteral("prnt_oresult"));
        prnt_oresult->setGeometry(QRect(550, 170, 171, 41));
        line = new QFrame(view_res);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(20, 240, 801, 31));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label_22 = new QLabel(view_res);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(370, 270, 131, 21));
        label_22->setFont(font5);
        label_23 = new QLabel(view_res);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(120, 330, 81, 41));
        label_23->setFont(font4);
        lineEdit_15 = new QLineEdit(view_res);
        lineEdit_15->setObjectName(QStringLiteral("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(220, 330, 501, 41));
        lineEdit_15->setMaxLength(10);
        view_presult = new QPushButton(view_res);
        view_presult->setObjectName(QStringLiteral("view_presult"));
        view_presult->setGeometry(QRect(220, 390, 171, 41));
        prnt_presult = new QPushButton(view_res);
        prnt_presult->setObjectName(QStringLiteral("prnt_presult"));
        prnt_presult->setGeometry(QRect(550, 390, 171, 41));
        tabWidget->addTab(view_res, QString());
        label = new QLabel(Home);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 10, 341, 71));
        label_2 = new QLabel(Home);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(670, 20, 181, 51));
        label_3 = new QLabel(Home);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(380, 30, 125, 31));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_3->setPalette(palette15);
        QFont font6;
        font6.setPointSize(24);
        font6.setBold(true);
        font6.setWeight(75);
        label_3->setFont(font6);
        progressBar = new QProgressBar(Home);
        progressBar->setObjectName(QStringLiteral("progressBar"));
        progressBar->setEnabled(true);
        progressBar->setGeometry(QRect(350, 86, 501, 15));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette16.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette16.setBrush(QPalette::Active, QPalette::HighlightedText, brush1);
        palette16.setBrush(QPalette::Active, QPalette::NoRole, brush1);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipBase, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::NoRole, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette16.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::NoRole, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush1);
        progressBar->setPalette(palette16);
        QFont font7;
        font7.setPointSize(9);
        font7.setBold(true);
        font7.setWeight(75);
        progressBar->setFont(font7);
        progressBar->setAutoFillBackground(false);
        progressBar->setValue(0);
        label_26 = new QLabel(Home);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(160, 657, 481, 20));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        label_26->setPalette(palette17);
        about = new QPushButton(Home);
        about->setObjectName(QStringLiteral("about"));
        about->setGeometry(QRect(760, 657, 91, 20));
        about->setFont(font7);
        label->raise();
        label_2->raise();
        label_3->raise();
        tabWidget->raise();
        progressBar->raise();
        label_26->raise();
        about->raise();

        retranslateUi(Home);

        tabWidget->setCurrentIndex(0);
        ad_judge->setDefault(true);


        QMetaObject::connectSlotsByName(Home);
    } // setupUi

    void retranslateUi(QDialog *Home)
    {
        Home->setWindowTitle(QApplication::translate("Home", "IMPETUS AND CONCEPTS  2017  HOME", 0));
        label_4->setText(QApplication::translate("Home", "JID              :", 0));
        label_5->setText(QApplication::translate("Home", "Name         :", 0));
        label_6->setText(QApplication::translate("Home", "Email ID     :", 0));
        label_7->setText(QApplication::translate("Home", "Domain Interest  ", 0));
        lineEdit->setPlaceholderText(QApplication::translate("Home", "*", 0));
        lineEdit_2->setPlaceholderText(QApplication::translate("Home", "*", 0));
        lineEdit_3->setPlaceholderText(QApplication::translate("Home", "*", 0));
        checkBox->setText(QApplication::translate("Home", "1. Networking And Information System Security", 0));
        checkBox_2->setText(QApplication::translate("Home", "2. Wireless & Mobile Based Communication and Applications", 0));
        checkBox_3->setText(QApplication::translate("Home", "3. Intelligent System, AI / Expert System / Pattern Recognition / Multimedia", 0));
        checkBox_4->setText(QApplication::translate("Home", "4. Communication System / VLSI / Embedded Technologies", 0));
        checkBox_5->setText(QApplication::translate("Home", "5. System Applications / Storage And Database", 0));
        checkBox_6->setText(QApplication::translate("Home", "6. Digital Signal Processing / Speech Processing / Image Processing", 0));
        checkBox_7->setText(QApplication::translate("Home", "7. Others	", 0));
        clear_judge->setText(QApplication::translate("Home", "Clear", 0));
        ad_judge->setText(QApplication::translate("Home", "ADD", 0));
        show_judge->setText(QApplication::translate("Home", "View Judges Info", 0));
        tabWidget->setTabText(tabWidget->indexOf(add_judge), QApplication::translate("Home", "Add Judge", 0));
        label_8->setText(QApplication::translate("Home", "PID              :", 0));
        label_9->setText(QApplication::translate("Home", "Category   :", 0));
        label_10->setText(QApplication::translate("Home", "Title             :", 0));
        label_11->setText(QApplication::translate("Home", "College     :", 0));
        label_12->setText(QApplication::translate("Home", "Group Member 1  :", 0));
        label_13->setText(QApplication::translate("Home", "Group Member 2  :", 0));
        label_14->setText(QApplication::translate("Home", "Group Member 3  :", 0));
        label_15->setText(QApplication::translate("Home", "Group Member 4  :", 0));
        label_16->setText(QApplication::translate("Home", "Group Member 5  :", 0));
        lineEdit_4->setPlaceholderText(QApplication::translate("Home", "*", 0));
        lineEdit_5->setPlaceholderText(QApplication::translate("Home", "*", 0));
        lineEdit_6->setPlaceholderText(QApplication::translate("Home", "*", 0));
        lineEdit_7->setText(QString());
        lineEdit_7->setPlaceholderText(QApplication::translate("Home", "* Group Leader ", 0));
        clear_group->setText(QApplication::translate("Home", "Clear", 0));
        ad_grp->setText(QApplication::translate("Home", "ADD", 0));
        show_grpinfo->setText(QApplication::translate("Home", "View Group Info", 0));
        label_24->setText(QApplication::translate("Home", "1. Networking And Information System Security\n"
"2. Wireless & Mobile Based Communication and Applications\n"
"3. Intelligent System, AI / Expert System / Pattern Recognition / Multimedia\n"
"4. Communication System / VLSI / Embedded Technologies\n"
"5. System Applications / Storage And Database\n"
"6. Digital Signal Processing / Speech Processing / Image Processing\n"
"7. Others	", 0));
        lineEdit_16->setPlaceholderText(QApplication::translate("Home", "*", 0));
        tabWidget->setTabText(tabWidget->indexOf(add_grp), QApplication::translate("Home", "Add Group", 0));
        label_17->setText(QApplication::translate("Home", "JID          :", 0));
        label_18->setText(QApplication::translate("Home", "PID          :", 0));
        label_19->setText(QApplication::translate("Home", "Marks     :", 0));
        lineEdit_14->setPlaceholderText(QApplication::translate("Home", "Out of 50", 0));
        clear_marks->setText(QApplication::translate("Home", "Clear", 0));
        ad_marks->setText(QApplication::translate("Home", "Add Marks", 0));
        show_marksentry->setText(QApplication::translate("Home", "View Marks entries", 0));
        label_25->setText(QApplication::translate("Home", "*Make sure that JID and PID exist in Database", 0));
        tabWidget->setTabText(tabWidget->indexOf(add_marks), QApplication::translate("Home", "Add Marks", 0));
        label_20->setText(QApplication::translate("Home", "Select Category :", 0));
        comboBox->clear();
        comboBox->insertItems(0, QStringList()
         << QApplication::translate("Home", "0 .    All Categories", 0)
         << QApplication::translate("Home", "1 .    Networking And Information System Security", 0)
         << QApplication::translate("Home", "2.     Wireless & Mobile Based Communication and Applications", 0)
         << QApplication::translate("Home", "3.     Intelligent System, AI / Expert System / Pattern Recognition / Multimedia", 0)
         << QApplication::translate("Home", "4.     Communication System / VLSI / Embedded Technologies", 0)
         << QApplication::translate("Home", "5.     System Applications / Storage And Database", 0)
         << QApplication::translate("Home", "6.     Digital Signal Processing / Speech Processing / Image Processing", 0)
         << QApplication::translate("Home", "7.     Others", 0)
        );
        label_21->setText(QApplication::translate("Home", "Overall Result", 0));
        view_oresult->setText(QApplication::translate("Home", "View Result", 0));
        prnt_oresult->setText(QApplication::translate("Home", "Print Result", 0));
        label_22->setText(QApplication::translate("Home", "Project Result", 0));
        label_23->setText(QApplication::translate("Home", "Select PID :", 0));
        view_presult->setText(QApplication::translate("Home", "View Result", 0));
        prnt_presult->setText(QApplication::translate("Home", "Print Result", 0));
        tabWidget->setTabText(tabWidget->indexOf(view_res), QApplication::translate("Home", "View Result", 0));
        label->setText(QString());
        label_2->setText(QString());
        label_3->setText(QApplication::translate("Home", "JUDGING", 0));
        label_26->setText(QApplication::translate("Home", "\302\251 PICT INC'17 All Rights Reserved 2017  |  Developed By Judging Team of INC '17", 0));
        about->setText(QApplication::translate("Home", "About Us", 0));
    } // retranslateUi

};

namespace Ui {
    class Home: public Ui_Home {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HOME_H
